name: Build CV on demand

on:
  workflow_dispatch:        # Enable manual call of this action

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4

      - name: ✨ Build documents
        uses: docker://xucheng/texlive-full:latest
        run: |
          find . -name "*.tex" -exec latexmk -pdf -file-line-error -interaction=nonstopmode {} \;

      - name: 🚀 Deploy
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: *.pdf
