name: Build CV on demand

on:
  workflow_dispatch:        # Enable manual call of this action

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4

      - name: ✨ Build CV
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            istvan_urban_cv_clean_short.tex
            istvan_urban_cv_clean_tldr.tex
            istvan_urban_cv_short.tex
            istvan_urban_cv_tldr.tex
          args: -output-directory=compiled
          latexmk_use_xelatex: true
          continue_on_error: true
          pre_compile: mkdir -p compiled
          post_compile: |
            rm -rf compiled/*.aux
            rm -rf compiled/*.log
            rm -rf compiled/*.fdb_latexmk
            rm -rf compiled/*.fls
            rm -rf compiled/*.xdv

      - name: 🚀 Deploy
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: compiled/*