name: Build CV on demand

on:
  workflow_dispatch:        # Enable manual call of this action

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4

      - name: ✨ Build CV
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
            make

      - name: 🚀 Deploy
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: compiled/*