name: Build CV on demand

on:
  workflow_dispatch:        # Enable manual call of this action

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4

      - name: ✨ Compile CV
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ls *.tex
          latexmk_use_xelatex: true
          continue_on_error: true

      - name: 🚀 Deploy
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: ls *.pdf
