name: Build tagged CV

on:
  push:
    tags:
      - "v*-*-*"  # Should be tagged like vYYYY-MM-DD

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4

      - name: ✨ Build CV
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            istvan_urban_cv_short.tex
            istvan_urban_cv_tldr.tex
            istvan_urban_cv_clean_short.tex
            istvan_urban_cv_clean_tldr.tex
          latexmk_use_xelatex: true
          continue_on_error: true

      - name: 🚀 Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            istvan_urban_cv_short.pdf
            istvan_urban_cv_tldr.pdf
            istvan_urban_cv_clean_short.pdf
            istvan_urban_cv_clean_tldr.pdf
