name: Build tagged CV

on:
  push:
    tags:
      - "v*-*-*"  # Should be tagged like vYYYY-MM-DD

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: ✨ Build CV
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make git
            mkdir -p compiled
            git config --system --add safe.directory '*'
            echo "# 📃 changelog" >> compiled/CHANGELOG
            echo >> compiled/CHANGELOG
            git log $(git describe --tags --abbrev=0 @^)..@ --oneline --date-order --pretty=format:"%h - %s" >> compiled/CHANGELOG
            make

      - name: 🚀 Release
        uses: softprops/action-gh-release@v1
        with:
          files: compiled/*.pdf
          body_path: compiled/CHANGELOG
