name: Build tagged CV

on:
  push:
    tags:
      - "v*-*-*"  # Should be tagged like vYYYY-MM-DD

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4

      - name: ✨ Build CV
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
            make

      - name: 📃 Generate CHANGELOG
        run: |
          echo "# 📃 changelog\n" >> compiled/CHANGELOG
          git log --oneline $(git describe --tags --abbrev=0 @^)..@ --pretty=format:"%h - %s" >> compiled/CHANGELOG

      - name: 🚀 Release
        uses: softprops/action-gh-release@v1
        with:
          files: compiled/*.pdf
          body_path: compiled/CHANGELOG
