name: Build CV for istvnurbn.me

on:
  push:
    tags:
      - "v*-*-*"  # Should be tagged like vYYYY-MM-DD
  workflow_dispatch:        # Enable manual call of this action

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4

      - name: ✨ Compile CV
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            istvan_urban_cv_clean_short.tex
            istvan_urban_cv_clean_tldr.tex
          args: -output-directory=compiled
          latexmk_use_xelatex: true
          continue_on_error: true
          pre_compile: mkdir -p compiled
          post_compile: |
            rm -rf compiled/*.aux
            rm -rf compiled/*.log
            rm -rf compiled/*.fdb_latexmk
            rm -rf compiled/*.fls
            rm -rf compiled/*.xdv
    
      - name: 🌍 Push to istvanurban.me
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'compiled'
          destination-github-username: 'istvnurbn'
          destination-repository-name: 'istvnurbn.github.io'
          target-branch: 'main'
          target-directory: 'assets/files'